'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import SocialFeed from './SocialFeed'

type Build={id:string;year:number;make:string;model:string;nickname?:string|null;coverUrl?:string|null;progress:number;owner:{username:string;displayName:string};_count:{comments:number;follows:number;reactions:number};liked?:boolean}
 type TrendingBuild=Build&{trendScore:number}
 type FeaturedBuild=Build&{featureScore:number}
type Answer={id:string;content:string;accepted:boolean;createdAt:string;author:{username:string;displayName:string}}
type Post={id:string;title:string;content:string;solved:boolean;createdAt:string;author:{username:string;displayName:string};build?:{id:string;year:number;make:string;model:string}|null;answers?:Answer[];_count?:{answers:number}}
type ActiveBuilder={id:string;username:string;displayName:string;bio?:string|null;avatarUrl?:string|null;buildsCount:number;postsCount:number;followersCount:number;recentBuilds:number;recentPosts:number;score:number;builds:{id:string;year:number;make:string;model:string;nickname?:string|null;progress:number;updatedAt:string;coverUrl?:string|null}[]}

export default function Community(){
 const [builds,setBuilds]=useState<Build[]>([]),[trending,setTrending]=useState<TrendingBuild[]>([]),[featured,setFeatured]=useState<FeaturedBuild[]>([]),[buildOfWeek,setBuildOfWeek]=useState<FeaturedBuild|null>(null),[posts,setPosts]=useState<Post[]>([]),[show,setShow]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true),[activeBuilders,setActiveBuilders]=useState<ActiveBuilder[]>([]),[query,setQuery]=useState(''),[filterMake,setFilterMake]=useState(''),[filterModel,setFilterModel]=useState(''),[filterYear,setFilterYear]=useState(''),[filterStatus,setFilterStatus]=useState(''),[mode,setMode]=useState<'latest'|'following'>('latest'),[unread,setUnread]=useState(0),[answerOpen,setAnswerOpen]=useState<string|null>(null),[answerText,setAnswerText]=useState('')
 async function load(q='',m: 'latest'|'following'=mode){setLoading(true);const params=new URLSearchParams();if(q)params.set('q',q);if(filterMake)params.set('make',filterMake);if(filterModel)params.set('model',filterModel);if(filterYear)params.set('year',filterYear);if(filterStatus)params.set('status',filterStatus);const url=m==='following'?'/api/feed':params.toString()?'/api/discover?'+params.toString():'/api/community';const r=await fetch(url);const d=await r.json();if(!r.ok)throw Error(d.error);setBuilds(d.builds||[]);if(m==='latest'&&!q){setPosts(d.posts||[]);setTrending(d.trending||[]);setFeatured(d.featured||[]);setBuildOfWeek(d.buildOfWeek||null)}setLoading(false)}
 async function refreshNotifications(){const r=await fetch('/api/notifications');if(r.ok){const d=await r.json();setUnread(d.unreadCount||0)}}
 async function search(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setMode('latest');try{await load(query,'latest')}catch(e){setError(e instanceof Error?e.message:'Search failed');setLoading(false)}}
 useEffect(()=>{load().catch(e=>{setError(e.message);setLoading(false)});refreshNotifications();fetch('/api/discover/active').then(r=>r.ok?r.json():null).then(d=>setActiveBuilders(d?.builders||[])).catch(()=>{})},[])
 async function switchMode(m:'latest'|'following'){setError('');setQuery('');setMode(m);try{await load('',m)}catch(e){if(m==='following'&&String(e).includes('Unauthorized')){location.href='/login';return}setError(e instanceof Error?e.message:'Could not load feed');setLoading(false)}}
 async function toggleLike(id:string){const r=await fetch('/api/builds/'+id+'/reaction',{method:'POST'});if(r.status===401){location.href='/login';return}const d=await r.json();if(!r.ok){setError(d.error||'Could not update like');return}setBuilds(bs=>bs.map(b=>b.id===id?{...b,liked:d.liked,_count:{...b._count,reactions:Math.max(0,b._count.reactions+(d.liked?1:-1))}}:b))}
 async function ask(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/community/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f.entries()))});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error);return}e.currentTarget.reset();setShow(false);await load('', 'latest')}
 async function answer(postId:string){const content=answerText.trim();if(!content)return;const r=await fetch('/api/community/posts/'+postId+'/answers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error||'Could not post answer');return}setAnswerText('');setAnswerOpen(null);setPosts(ps=>ps.map(p=>p.id===postId?{...p,answers:[...(p.answers||[]),d.answer],_count:{answers:(p._count?.answers||0)+1}}:p))}
 async function accept(postId:string,answerId:string){const r=await fetch('/api/community/posts/'+postId+'/answers',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({answerId})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error||'Could not accept answer');return}setPosts(ps=>ps.map(p=>p.id===postId?{...p,solved:true,answers:(p.answers||[]).map(a=>({...a,accepted:a.id===answerId}))}:p))}
 return <main className="dashboard"><header className="topbar"><div className="topbar-inner"><Link className="brand" href="/">BUILD<span>TRACK</span></Link><nav className="community-nav"><Link href="/community">Community</Link><Link href="/notifications" className="activity-link">🔔 Activity{unread>0&&<span className="notification-badge">{unread>99?'99+':unread}</span>}</Link><Link href="/dashboard">Garage</Link><Link className="btn btn-primary" href="/register">Join</Link></nav></div></header>
 <section className="dash-main"><div className="community-hero"><div><div className="eyebrow">BUILDTRACK COMMUNITY</div><h1>{mode==='following'?'Your feed.':'See what people are building.'}</h1><p className="muted">{mode==='following'?'Latest updates from builders and projects you follow.':'Discover builds, follow projects, and get real answers from other builders.'}</p></div><button className="btn btn-primary" onClick={()=>setShow(!show)}>＋ Ask the community</button></div>
  {mode==='latest'&&!query&&buildOfWeek&&<section className="featured-hero"><div className="featured-copy"><div className="eyebrow">⭐ BUILD OF THE WEEK</div><h2>{buildOfWeek.year} {buildOfWeek.make} {buildOfWeek.model}</h2><p>{buildOfWeek.nickname||'Featured build'} · {buildOfWeek.progress}% complete · {buildOfWeek._count.reactions} likes · {buildOfWeek._count.comments} comments</p><Link className="btn btn-primary" href={'/builds/'+buildOfWeek.id}>View featured build →</Link></div>{buildOfWeek.coverUrl&&<img src={buildOfWeek.coverUrl} alt=""/>}</section>}
  {mode==='latest'&&!query&&<section><div className="section-heading-row"><h2 className="section-title">Featured builds</h2><span className="muted">Updated this week</span></div><div className="featured-grid">{featured.map((b,i)=><Link className="featured-card" href={'/builds/'+b.id} key={b.id}>{b.coverUrl&&<img src={b.coverUrl} alt=""/>}<div className="featured-card-body"><span className="featured-rank">FEATURED #{i+1}</span><h3>{b.year} {b.make} {b.model}</h3><p>{b.nickname||'Build project'} · {b.progress}% complete</p><small>{b._count.reactions} likes · {b._count.comments} comments · {b._count.follows} followers</small></div></Link>)}</div></section>}
  {mode==='latest'&&!query&&!filterMake&&!filterModel&&!filterYear&&!filterStatus&&activeBuilders.length>0&&<section className="active-builders"><div className="section-heading-row"><div><h2 className="section-title">Active builders</h2><p className="muted">Builders who have been updating projects or posting in the last 30 days.</p></div><span className="muted">12 spots</span></div><div className="active-builder-grid">{activeBuilders.map((u,i)=><Link className="active-builder-card" href={'/users/'+u.username} key={u.id}><div className="active-builder-head">{u.avatarUrl?<img src={u.avatarUrl} alt=""/>:<div className="active-builder-avatar">{u.displayName.slice(0,1).toUpperCase()}</div>}<div><b>{u.displayName}</b><small>@{u.username}</small></div><span className="active-rank">#{i+1}</span></div><div className="active-builder-stats"><span><b>{u.recentPosts}</b> recent posts</span><span><b>{u.recentBuilds}</b> active builds</span><span><b>{u.followersCount}</b> followers</span></div>{u.builds[0]&&<div className="active-build-preview">{u.builds[0].coverUrl&&<img src={u.builds[0].coverUrl} alt=""/>}<div><small>LAST BUILD UPDATE</small><b>{u.builds[0].year} {u.builds[0].make} {u.builds[0].model}</b><span>{u.builds[0].progress}% complete</span></div></div>}<span className="small-link">View builder →</span></Link>)}</div></section>}
  <SocialFeed />
  <div className="feed-tabs"><button className={'btn '+(mode==='latest'?'btn-primary':'btn-ghost')} onClick={()=>switchMode('latest')}>Latest</button><button className={'btn '+(mode==='following'?'btn-primary':'btn-ghost')} onClick={()=>switchMode('following')}>Following</button></div>
  {mode==='latest'&&<form className="discover-search" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search builds, cars, builders, or nicknames…" aria-label="Search community"/><input value={filterMake} onChange={e=>setFilterMake(e.target.value)} placeholder="Make" aria-label="Filter by make"/><input value={filterModel} onChange={e=>setFilterModel(e.target.value)} placeholder="Model" aria-label="Filter by model"/><input value={filterYear} onChange={e=>setFilterYear(e.target.value.slice(0,4))} placeholder="Year" inputMode="numeric" aria-label="Filter by year"/><select value={filterStatus} onChange={e=>setFilterStatus(e.target.value)} aria-label="Filter by build status"><option value="">Any status</option><option value="not-started">Not started</option><option value="in-progress">In progress</option><option value="complete">Complete</option></select><button className="btn btn-primary">Search</button>{(query||filterMake||filterModel||filterYear||filterStatus)&&<button type="button" className="btn btn-ghost" onClick={()=>{setQuery('');setFilterMake('');setFilterModel('');setFilterYear('');setFilterStatus('');load().catch(e=>setError(e.message))}}>Clear</button>}</form>}
  {show&&<form className="panel form" onSubmit={ask}><h2>Ask for help</h2><input name="title" placeholder="What are you working on?" required/><textarea name="content" placeholder="Explain the problem or question…" required/><input name="buildId" placeholder="Optional build ID"/><button className="btn btn-primary">Post question</button></form>}
  {error&&<div className="error">{error}</div>}
  {loading?<p className="muted">Loading community…</p>:<div className="community-layout"><div><h2 className="section-title">{(query||filterMake||filterModel||filterYear||filterStatus)?'Discovery results':mode==='following'?'Following builds':'Latest builds'}</h2>{mode==='following'&&!builds.length?<div className="empty"><h2>Your feed is empty.</h2><p className="muted">Follow a builder or build to see their updates here.</p><Link className="btn btn-primary" href="/community">Discover builds</Link></div>:<div className="build-grid community-builds">{builds.map(b=><div className="build-card" key={b.id}><Link href={'/builds/'+b.id}>{b.coverUrl&&<img className="build-card-image" src={b.coverUrl} alt=""/>}<div className="build-meta">{b.year} {b.make}</div><h2>{b.model}</h2><p className="muted">{b.nickname||'Build project'} · {b.progress}% complete</p><p className="muted">by <b>{b.owner.displayName}</b> · {b._count.comments} comments · {b._count.follows} followers</p></Link><div className="card-social"><button className={'btn btn-ghost like-btn '+(b.liked?'liked':'')} onClick={()=>toggleLike(b.id)}>{b.liked?'♥ Liked':'♡ Like'} · {b._count.reactions}</button><Link className="small-link" href={'/builds/'+b.id}>View build →</Link></div></div>)}</div>}</div>
   <div>{mode==='latest'&&!query&&<><h2 className="section-title">Trending builds</h2><div className="trending-list">{trending.map((b,i)=><Link className="trending-card" href={'/builds/'+b.id} key={b.id}><span className="trending-rank">{i+1}</span>{b.coverUrl&&<img src={b.coverUrl} alt=""/>}<div><b>{b.year} {b.make} {b.model}</b><small>{b.nickname||'Build project'} · {b._count.reactions} likes · {b._count.comments} comments</small></div></Link>)}</div></>}<h2 className="section-title">Help wanted</h2><div className="list">{posts.map(p=><article className="panel help-card" key={p.id}><div className="help-status"><span className={'status-pill '+(p.solved?'status-done':'status-open')}>{p.solved?'✓ SOLVED':'OPEN'}</span><small>by <Link className="small-link" href={'/users/'+p.author.username}>{p.author.displayName}</Link> · {new Date(p.createdAt).toLocaleDateString()}</small></div><h3>{p.title}</h3><p>{p.content}</p>{p.build&&<Link className="small-link" href={'/builds/'+p.build.id}>View {p.build.year} {p.build.make} {p.build.model} →</Link>}<div className="answer-list">{(p.answers||[]).map(a=><div className={'answer '+(a.accepted?'accepted-answer':'')} key={a.id}><div><b>{a.author.displayName}</b><small> · {new Date(a.createdAt).toLocaleDateString()}</small></div><p>{a.content}</p>{a.accepted&&<span className="accepted-label">✓ Accepted solution</span>}{!a.accepted&&<button className="btn btn-ghost" onClick={()=>accept(p.id,a.id)}>Accept solution</button>}</div>)}</div><div className="answer-actions"><button className="btn btn-ghost" onClick={()=>setAnswerOpen(answerOpen===p.id?null:p.id)}>💬 Answer · {p._count?.answers||0}</button></div>{answerOpen===p.id&&<div className="answer-form"><textarea value={answerText} onChange={e=>setAnswerText(e.target.value)} placeholder="Share what you know…" maxLength={2000}/><button className="btn btn-primary" onClick={()=>answer(p.id)}>Post answer</button></div>}</article>)}</div>{!posts.length&&mode==='latest'&&<div className="empty"><p className="muted">No questions yet. Be the first.</p></div>}</div></div>}
 </section></main>
}
