'use client'
import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'

type Post={id:string;content:string;imageUrl?:string|null;createdAt:string;liked:boolean;_count:{likes:number;comments:number};author:{username:string;displayName:string;avatarUrl?:string|null};build?:{id:string;year:number;make:string;model:string;nickname?:string|null;coverUrl?:string|null}|null;comments:{id:string;content:string;createdAt:string;user:{username:string;displayName:string}}[]}

type Build={id:string;year:number;make:string;model:string;nickname?:string|null}
export default function SocialFeed(){
 const [posts,setPosts]=useState<Post[]>([]),[content,setContent]=useState(''),[buildId,setBuildId]=useState(''),[following,setFollowing]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[comment,setComment]=useState<Record<string,string>>({}),[builds,setBuilds]=useState<Build[]>([])
 async function load(){setLoading(true);const r=await fetch('/api/social/posts'+(following?'?following=true':''));const d=await r.json();if(!r.ok){setError(d.error||'Could not load feed');setLoading(false);return}setPosts(d.posts||[]);setLoading(false)}
 useEffect(()=>{load()},[following])
 useEffect(()=>{fetch('/api/builds').then(r=>r.ok?r.json():null).then(d=>setBuilds(d?.builds||[])).catch(()=>{})},[])
 async function publish(e:FormEvent){e.preventDefault();setError('');if(!content.trim())return;const r=await fetch('/api/social/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content,buildId:buildId||undefined})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error||'Could not publish');return}setContent('');setBuildId('');await load()}
 async function like(id:string){const r=await fetch('/api/social/posts/'+id+'/like',{method:'POST'});if(r.status===401){location.href='/login';return}const d=await r.json();if(!r.ok){setError(d.error);return}setPosts(ps=>ps.map(p=>p.id===id?{...p,liked:d.liked,_count:{...p._count,likes:d.count}}:p))}
 async function addComment(id:string){const text=(comment[id]||'').trim();if(!text)return;const r=await fetch('/api/social/posts/'+id+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error);return}setComment(c=>({...c,[id]:''}));setPosts(ps=>ps.map(p=>p.id===id?{...p,comments:[...p.comments,d.comment],_count:{...p._count,comments:p._count.comments+1}}:p))}
 return <section className="social-feed"><div className="section-heading"><div><div className="eyebrow">BUILDTRACK SOCIAL</div><h2>Build updates</h2><p className="muted">Share progress, ask questions, and see what other builders are doing.</p></div><div className="feed-tabs"><button type="button" className={'btn '+(!following?'btn-primary':'btn-ghost')} onClick={()=>setFollowing(false)}>Everyone</button><button type="button" className={'btn '+(following?'btn-primary':'btn-ghost')} onClick={()=>setFollowing(true)}>Following</button></div></div>
 <form className="panel social-composer" onSubmit={publish}><textarea value={content} onChange={e=>setContent(e.target.value)} maxLength={5000} required placeholder="What are you working on today? Share a build update…"/><div className="composer-row"><select value={buildId} onChange={e=>setBuildId(e.target.value)} aria-label="Attach a build"><option value="">Attach a build (optional)</option>{builds.map(b=><option key={b.id} value={b.id}>{b.year} {b.make} {b.model}{b.nickname?' · '+b.nickname:''}</option>)}</select><span className="muted">{content.length}/5000</span><button className="btn btn-primary">Post update</button></div></form>
 {error&&<div className="error">{error}</div>}{loading?<p className="muted">Loading updates…</p>:!posts.length?<div className="empty"><h3>{following?'No updates from people or builds you follow yet.':'No build updates yet.'}</h3><p className="muted">Be the first builder to share what you're working on.</p></div>:<div className="social-list">{posts.map(p=><article className="panel social-card" key={p.id}><div className="social-author"><div className="avatar">{p.author.displayName.slice(0,1).toUpperCase()}</div><div><Link href={'/users/'+p.author.username}><b>{p.author.displayName}</b></Link><div className="muted">@{p.author.username} · {new Date(p.createdAt).toLocaleString()}</div></div></div><p className="social-content">{p.content}</p>{p.build&&<Link className="build-chip" href={'/builds/'+p.build.id}>{p.build.coverUrl&&<img className="build-chip-image" src={p.build.coverUrl} alt=""/>}🏎️ {p.build.year} {p.build.make} {p.build.model}{p.build.nickname?' · '+p.build.nickname:''}</Link>}{p.imageUrl&&<img className="social-image" src={p.imageUrl} alt="Build update"/>}<div className="social-actions"><button type="button" className={'btn btn-ghost '+(p.liked?'liked':'')} onClick={()=>like(p.id)}>{p.liked?'♥ Liked':'♡ Like'} · {p._count.likes}</button><span className="muted">💬 {p._count.comments}</span></div><div className="social-comments">{p.comments.map(c=><div className="social-comment" key={c.id}><b>{c.user.displayName}</b><span>{c.content}</span></div>)}<div className="comment-row"><input value={comment[p.id]||''} onChange={e=>setComment(c=>({...c,[p.id]:e.target.value}))} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();addComment(p.id)}}} placeholder="Write a comment…" maxLength={2000}/><button type="button" className="btn btn-ghost" onClick={()=>addComment(p.id)}>Send</button></div></div></article>)}</div>}
 </section>
}
