'use client'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'

type User={username:string;displayName:string;bio?:string|null;avatarUrl?:string|null;createdAt:string;isOwner?:boolean;_count:{builds:number;followsFollowers:number;followsFollowing:number;socialPosts:number;socialLikes:number};builds:any[];socialPosts:any[]}
type Achievement={icon:string;title:string;text:string;target:number;value:number;unit:string}
export default function Profile(){
 const {username}=useParams<{username:string}>(); const [user,setUser]=useState<User|null>(null),[following,setFollowing]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[posting,setPosting]=useState(false),[postCaption,setPostCaption]=useState(''),[postHashtags,setPostHashtags]=useState(''),[postBuild,setPostBuild]=useState(''),[postImage,setPostImage]=useState(''),[postPreview,setPostPreview]=useState(''),[selectedPost,setSelectedPost]=useState<any|null>(null),[showComposer,setShowComposer]=useState(false),[profileSaving,setProfileSaving]=useState(false),[profileBio,setProfileBio]=useState(''),[profileImage,setProfileImage]=useState(''),[profilePreview,setProfilePreview]=useState(''),[showProfileEditor,setShowProfileEditor]=useState(false)
 useEffect(()=>{fetch('/api/users/'+username).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setUser(d.user);setProfileBio(d.user.bio||'');setProfilePreview(d.user.avatarUrl||'')}).catch(e=>setError(e.message));fetch('/api/users/'+username+'/follow').then(async r=>{if(r.ok){const d=await r.json();setFollowing(!!d.following)}}).catch(()=>{})},[username])
 async function toggle(){setBusy(true);const r=await fetch('/api/users/'+username+'/follow',{method:following?'DELETE':'POST'});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error)}else setFollowing(d.following);setBusy(false)}
 async function compressImage(file:File){return new Promise<string>((resolve,reject)=>{if(!file.type.startsWith('image/'))return reject(Error('Please choose an image file.'));const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const max=2000;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return reject(Error('Could not process image.'));ctx.drawImage(img,0,0,canvas.width,canvas.height);const data=canvas.toDataURL('image/jpeg',.82);if(data.length>2800000)return reject(Error('That photo is still too large. Please choose a smaller image.'));resolve(data)};img.onerror=()=>reject(Error('Could not read image.'));img.src=String(reader.result)};reader.onerror=()=>reject(Error('Could not read image.'));reader.readAsDataURL(file)})}
 async function choosePostImage(file?:File){if(!file)return;setError('');try{const data=await compressImage(file);setPostImage(data);setPostPreview(data)}catch(e){setError(e instanceof Error?e.message:'Could not process photo.');setPostImage('');setPostPreview('')}}
 async function saveProfile(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setProfileSaving(true);const r=await fetch('/api/users/'+username,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({bio:profileBio,avatarUrl:profileImage||null})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error||'Could not update profile.');setProfileSaving(false);return}setUser(u=>u?{...u,...d.user}:u);setProfileSaving(false);setShowProfileEditor(false)}
 async function chooseProfileImage(file?:File){if(!file)return;setError('');try{const data=await compressImage(file);setProfileImage(data);setProfilePreview(data)}catch(e){setError(e instanceof Error?e.message:'Could not process profile photo.');setProfileImage('');setProfilePreview(user?.avatarUrl||'')}}
 async function createPost(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(!postCaption.trim())return setError('Add a caption before posting.');setPosting(true);const r=await fetch('/api/social/posts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:postCaption.trim(),hashtags:postHashtags.trim(),imageUrl:postImage||null,buildId:postBuild||null})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error||'Could not create post.');setPosting(false);return}setPostCaption('');setPostHashtags('');setPostBuild('');setPostImage('');setPostPreview('');setPosting(false);await refreshProfile()}
 async function refreshProfile(){const r=await fetch('/api/users/'+username);const d=await r.json();if(r.ok)setUser(d.user)}
 if(error&&!user)return <main className="auth-wrap"><div className="auth-card"><p className="error">{error}</p><Link href="/community" className="small-link">Back to community</Link></div></main>
 if(!user)return <main className="auth-wrap"><p className="muted">Loading profile…</p></main>
 const achievements:Achievement[]=[
  {icon:'🏁',title:'First Build',text:'Start your garage journey',target:1,value:user._count.builds,unit:'build'},
  {icon:'🔧',title:'Multi-Build',text:'Track three builds',target:3,value:user._count.builds,unit:'builds'},
  {icon:'🏆',title:'Garage Builder',text:'Track five builds',target:5,value:user._count.builds,unit:'builds'},
  {icon:'📣',title:'Active Builder',text:'Share five community updates',target:5,value:user._count.socialPosts,unit:'updates'},
  {icon:'🔥',title:'Build Regular',text:'Share ten community updates',target:10,value:user._count.socialPosts,unit:'updates'},
  {icon:'🤝',title:'Community Builder',text:'Reach ten followers',target:10,value:user._count.followsFollowers,unit:'followers'}
 ]
 const earned=achievements.filter(a=>a.value>=a.target).length
 const achievementStyles=<style>{`.achievement-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:20px}.achievement-heading h2{font-family:'Barlow Condensed',sans-serif;font-size:30px;text-transform:uppercase;margin:0 0 6px}.achievement-count{font-family:'Barlow Condensed',sans-serif;font-size:24px;color:#ff7135;white-space:nowrap}.achievement-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px}.achievement{display:flex;gap:12px;min-height:112px;background:#090d11;border:1px solid #202a33;border-radius:12px;padding:14px}.achievement.earned{border-color:#3b4651}.achievement.locked{opacity:.68}.achievement-icon{width:38px;height:38px;display:grid;place-items:center;background:#151c22;border-radius:10px;font-size:20px;flex:0 0 auto}.achievement.earned .achievement-icon{background:#ff5a1618}.achievement-body{min-width:0;flex:1}.achievement-title{display:flex;justify-content:space-between;gap:8px}.achievement-title b{font-size:13px}.achievement-title span{font-size:10px;color:#818b96;white-space:nowrap}.achievement-body small{display:block;color:#818b96;line-height:1.35;margin-top:5px;min-height:27px}.achievement-progress{height:6px;background:#242c34;border-radius:20px;overflow:hidden;margin:10px 0 6px}.achievement-progress i{display:block;height:100%;background:linear-gradient(90deg,#ff5a16,#ff9a4d)}.achievement-body em{font-style:normal;font-size:9px;color:#ff7135;font-weight:800;text-transform:uppercase;letter-spacing:.7px}.achievement.locked .achievement-body em{color:#818b96}@media(max-width:900px){.achievement-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.achievement-grid{grid-template-columns:1fr}.achievement-heading{flex-direction:column}}`}</style>
 return <>{achievementStyles}<main className="dashboard"><header className="topbar"><div className="topbar-inner"><Link className="brand" href="/">BUILD<span>TRACK</span></Link><div className="community-nav"><Link href="/community">Community</Link><Link href="/leaderboard">🏆 Leaderboard</Link><Link href="/notifications">Activity</Link><Link href="/dashboard">Garage</Link></div></div></header><section className="dash-main">
 <div className="profile-hero">
  <div className="profile-identity">
   <div className="profile-avatar-wrap">
    <div className="avatar">{user.avatarUrl?<img src={user.avatarUrl} alt={user.displayName}/>:user.displayName.slice(0,1).toUpperCase()}</div>
   </div>
   <div className="profile-identity-copy">
    <h1>{user.displayName}</h1>
    <p className="muted">@{user.username}</p>
    {user.isOwner ? (
      <>
       <button type="button" className="btn btn-primary profile-edit-toggle" onClick={()=>setShowProfileEditor(v=>!v)}>{showProfileEditor?'Close editor':'✏️ Edit profile'}</button>
       {showProfileEditor && (
        <form className="profile-bio-form" onSubmit={saveProfile}>
         <label className="profile-avatar-edit"><span>{profilePreview?'Change profile photo':'Add profile photo'}</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>chooseProfileImage(e.target.files?.[0])}/></label>
         <textarea value={profileBio} onChange={e=>setProfileBio(e.target.value)} maxLength={500} placeholder="Tell the community about yourself and your builds..."/>
         <div className="profile-bio-actions"><span className="muted">Your bio is public · 500 characters max</span><button className="btn btn-primary" disabled={profileSaving}>{profileSaving?'Saving…':'Save profile'}</button></div>
        </form>
       )}
      </>
    ) : (
      <p className="public-description">{user.bio||'Building cars and sharing the process.'}</p>
    )}
    <div className="profile-stats"><span><b>{user._count.builds}</b> builds</span><span><b>{user._count.socialPosts}</b> updates</span><span><b>{user._count.followsFollowers}</b> followers</span><span><b>{user._count.followsFollowing}</b> following</span></div>
   </div>
  </div>
  <button className="btn btn-primary" onClick={toggle} disabled={busy}>{following?'Following':'Follow builder'}</button>
 </div>
 <div className="panel reputation-panel"><div className="achievement-heading"><div><h2>Builder achievements</h2><p className="muted">{earned} of {achievements.length} milestones earned. Keep building, sharing and connecting.</p></div><span className="achievement-count">{earned}/{achievements.length} 🏆</span></div><div className="achievement-grid">{achievements.map(a=>{const complete=a.value>=a.target;const progress=Math.min(100,Math.round(a.value/a.target*100));return <div className={'achievement '+(complete?'earned':'locked')} key={a.title}><div className="achievement-icon">{complete?a.icon:'🔒'}</div><div className="achievement-body"><div className="achievement-title"><b>{a.title}</b><span>{Math.min(a.value,a.target)}/{a.target}</span></div><small>{a.text}</small><div className="achievement-progress"><i style={{width:progress+'%'}}/></div><em>{complete?'Unlocked':`${Math.min(a.value,a.target)} / ${a.target} ${a.unit}`}</em></div></div>})}</div></div>
 <section className="panel profile-post-composer"><div className="post-composer-heading"><div><div className="eyebrow">SHARE YOUR BUILD</div><h2>Create a post</h2><p className="muted">Share photos, captions, hashtags and tagged builds with the community.</p></div><button type="button" className="btn btn-primary" onClick={()=>setShowComposer(v=>!v)}>{showComposer?"Close upload":"📷 Upload a post"}</button></div>{showComposer&&<form className="post-composer-form" onSubmit={createPost}><label className="post-photo-picker">{postPreview?<img src={postPreview} alt="Post preview"/>:<span>📷 Add a photo</span>}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>choosePostImage(e.target.files?.[0])}/></label><textarea value={postCaption} onChange={e=>setPostCaption(e.target.value)} placeholder="What's happening with your build?" maxLength={5000} required/><input value={postHashtags} onChange={e=>setPostHashtags(e.target.value)} placeholder="#EvoX #BuildTrack #CarBuild" maxLength={500}/><select value={postBuild} onChange={e=>setPostBuild(e.target.value)}><option value="">Tag one of my builds (optional)</option>{user.builds.map(b=><option key={b.id} value={b.id}>{b.year} {b.make} {b.model}{b.nickname?' · '+b.nickname:''}</option>)}</select><div className="post-composer-actions"><span className="muted">Photo + caption + hashtags</span><button className="btn btn-primary" disabled={posting}>{posting?'Posting…':'Share post'}</button></div></form>}</section>
 <div className="profile-showcase"><div><h2 className="section-title">Garage showcase</h2><div className="build-grid">{user.builds.map(b=><Link href={'/builds/'+b.id} className="build-card" key={b.id}>{b.coverUrl&&<img className="build-card-image" src={b.coverUrl} alt=""/>}<div className="build-meta">{b.year} {b.make}</div><h2>{b.model}</h2><p className="muted">{b.nickname||'Build project'} · {b.progress}% complete</p><div className="progress"><i style={{width:b.progress+'%'}}/></div><p className="muted">{b._count.comments} comments · {b._count.follows} followers · {b._count.reactions} likes</p></Link>)}</div>{!user.builds.length&&<div className="empty"><p className="muted">No public builds yet.</p></div>}</div>
 <div><h2 className="section-title">Posts</h2><div className="profile-post-grid">{user.socialPosts.map(p=><button type="button" className="profile-post-tile" key={p.id} onClick={()=>setSelectedPost(p)} aria-label={`Open post from ${user.displayName}`}>{p.imageUrl?<img src={p.imageUrl} alt=""/>:<div className="profile-post-tile-placeholder">BUILD<br/>TRACK</div>}<div className="profile-post-tile-overlay"><span>♥ {p._count.likes}</span><span>💬 {p._count.comments}</span></div></button>)}</div>{!user.socialPosts.length&&<div className="empty"><p className="muted">No posts yet.</p></div>}</div></div>
 {selectedPost&&<div className="post-modal-backdrop" role="presentation" onClick={()=>setSelectedPost(null)}><div className="post-modal" role="dialog" aria-modal="true" aria-label="Post details" onClick={e=>e.stopPropagation()}><button type="button" className="post-modal-close" onClick={()=>setSelectedPost(null)} aria-label="Close post">×</button>{selectedPost.imageUrl&&<img className="post-modal-image" src={selectedPost.imageUrl} alt=""/>}<div className="post-modal-body"><div className="post-modal-author"><div className="avatar small">{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:user.displayName.slice(0,1).toUpperCase()}</div><div><strong>{user.displayName}</strong><span className="muted">@{user.username}</span></div></div><p className="post-modal-caption">{selectedPost.content}</p>{selectedPost.hashtags&&<div className="profile-hashtags">{selectedPost.hashtags.split(/\s+/).filter(Boolean).map((tag:string)=><span key={tag}>{tag.startsWith('#')?tag:'#'+tag}</span>)}</div>}{selectedPost.build&&<Link className="build-chip post-modal-build" href={'/builds/'+selectedPost.build.id}>{selectedPost.build.coverUrl&&<img className="build-chip-image" src={selectedPost.build.coverUrl} alt=""/>}🏎️ Tagged build: {selectedPost.build.year} {selectedPost.build.make} {selectedPost.build.model}{selectedPost.build.nickname?' · '+selectedPost.build.nickname:''}</Link>}<div className="muted profile-update-meta">{new Date(selectedPost.createdAt).toLocaleDateString()} · ♥ {selectedPost._count.likes} · 💬 {selectedPost._count.comments}</div></div></div></div>} </section></main></>
}
