'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'

type Entry={progress:number;completedAt:string|null;user:{username:string;displayName:string;avatarUrl:string|null}}
type Challenge={id:string;slug:string;title:string;description:string;icon:string;metric:string;target:number;startsAt:string;endsAt:string;entries:Entry[];_count:{entries:number}}

export default function Challenges(){
 const [items,setItems]=useState<Challenge[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 useEffect(()=>{fetch('/api/challenges').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load challenges');setItems(d.challenges||[])}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
 return <main className="dashboard"><header className="topbar"><div className="topbar-inner"><Link className="brand" href="/">BUILD<span>TRACK</span></Link><nav className="community-nav"><Link href="/community">Community</Link><Link href="/leaderboard">🏆 Leaderboard</Link><Link href="/notifications">🔔 Activity</Link><Link href="/dashboard">Garage</Link></nav></div></header><section className="dash-main"><div className="community-hero"><div><div className="eyebrow">SEASONAL COMPETITION</div><h1>Challenges.</h1><p className="muted">Join community challenges, track progress and earn recognition for building and sharing.</p></div><Link className="btn btn-primary" href="/community">Back to community</Link></div>{error&&<div className="error">{error}</div>}{loading?<p className="muted">Loading challenges…</p>:!items.length?<div className="panel empty"><h2>No active challenges</h2><p className="muted">New community challenges will appear here when they launch.</p></div>:<div className="challenge-grid">{items.map(c=><article className="challenge-card" key={c.id}><div className="challenge-icon">{c.icon}</div><div className="eyebrow">ENDS {new Date(c.endsAt).toLocaleDateString()}</div><h2>{c.title}</h2><p className="muted">{c.description}</p><div className="challenge-target"><b>{c.target}</b><span>{c.metric}</span></div><div className="challenge-meta"><span>{c._count.entries} builders joined</span><span>Top 10</span></div><div className="challenge-leaders">{c.entries.slice(0,5).map((e,i)=><Link href={'/users/'+e.user.username} key={e.user.username}><span className="challenge-rank">#{i+1}</span>{e.user.avatarUrl?<img src={e.user.avatarUrl} alt=""/>:<span className="leaderboard-avatar">{e.user.displayName.slice(0,1)}</span>}<b>{e.user.displayName}</b><strong>{Math.min(e.progress,c.target)}/{c.target}</strong></Link>)}</div></article>)}</div>}</section></main>
}
