import Link from 'next/link'

export default function Home() {
  return <main className="home">
    <nav className="nav"><Link className="brand" href="/">BUILD<span>TRACK</span></Link><div className="nav-links"><Link href="/community">Community</Link><Link href="/dashboard">Garage</Link><Link href="/login">Log in</Link><Link className="btn btn-primary" href="/register">Create account</Link></div></nav>
    <section className="hero"><div className="eyebrow">AUTOMOTIVE BUILD COMMUNITY</div><h1>Build it.<br/><span>Track it.</span><br/>Share it.</h1><p>Track your car build, discover what other enthusiasts are building, follow projects, share progress and get help when you're stuck.</p><div className="hero-actions"><Link className="btn btn-primary btn-large" href="/community">Explore the community →</Link><Link className="btn btn-secondary btn-large" href="/register">Start your garage</Link></div></section>
    <section className="feature-grid"><Link href="/dashboard" className="feature"><div className="feature-icon">01</div><h2>Your Garage</h2><p>Create vehicles and keep every build in one place.</p><strong>Open Garage →</strong></Link><Link href="/builds/new" className="feature"><div className="feature-icon">02</div><h2>Build Tracking</h2><p>Track progress, budget, parts, tasks, expenses and your build journal.</p><strong>Add a Vehicle →</strong></Link><Link href="/community" className="feature"><div className="feature-icon">03</div><h2>Community</h2><p>Discover public builds, follow builders, comment on projects and ask for help.</p><strong>Explore Community →</strong></Link></section>
    <section className="demo"><div><div className="eyebrow">BUILDTRACK COMMUNITY IS LIVE</div><h2>Your build is more than a parts list.</h2><p>Document the work, meet other builders and build a history of the car.</p></div><Link className="btn btn-primary" href="/community">See what people are building</Link></section>
  </main>
}