'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'

type Build={id:string;year:number;make:string;model:string;nickname?:string|null;owner:{username:string;displayName:string}}
type Feature={id:string;buildId:string;kind:string;startAt:string;endAt:string|null;build:Build}

export default function FeaturedAdmin(){
 const [builds,setBuilds]=useState<Build[]>([]),[features,setFeatures]=useState<Feature[]>([]),[buildId,setBuildId]=useState(''),[kind,setKind]=useState<'week'|'featured'>('featured'),[startAt,setStartAt]=useState(''),[endAt,setEndAt]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function load(){setLoading(true);const r=await fetch('/api/admin/featured');const d=await r.json();if(!r.ok){setError(d.error||'Could not load admin controls');setLoading(false);return}setBuilds(d.builds||[]);setFeatures(d.features||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 async function save(e:FormEvent){e.preventDefault();setError('');setMessage('');const r=await fetch('/api/admin/featured',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({buildId,kind,startAt:startAt||undefined,endAt:endAt||undefined})});const d=await r.json();if(!r.ok){setError(d.error||'Could not feature build');return}setMessage(kind==='week'?'Build of the Week updated.':'Featured build updated.');setBuildId('');await load()}
 async function remove(id:string){if(!confirm('Remove this feature?'))return;const r=await fetch('/api/admin/featured',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const d=await r.json();if(!r.ok){setError(d.error||'Could not remove feature');return}await load()}
 return <main className="dashboard"><header className="topbar"><div className="topbar-inner"><Link className="brand" href="/">BUILD<span>TRACK</span></Link><nav className="community-nav"><Link href="/community">Community</Link><Link href="/dashboard">Garage</Link></nav></div></header><section className="admin-layout"><div className="admin-toolbar"><div><div className="eyebrow">BUILDTRACK ADMIN</div><h1>Featured Builds</h1><p className="muted">Manually control Build of the Week and community featured spots.</p></div><Link className="btn btn-ghost" href="/community">← Back to Community</Link></div>{error&&<div className="error">{error}</div>}{message&&<div className="panel">{message}</div>}{loading?<p className="muted">Loading admin controls…</p>:<div className="admin-grid"><section className="panel"><h2>Feature a build</h2><form className="admin-form" onSubmit={save}><label>Build<select value={buildId} onChange={e=>setBuildId(e.target.value)} required><option value="">Select a build…</option>{builds.map(b=><option key={b.id} value={b.id}>{b.year} {b.make} {b.model}{b.nickname?' — '+b.nickname:''} · @{b.owner.username}</option>)}</select></label><label>Spotlight<select value={kind} onChange={e=>setKind(e.target.value as 'week'|'featured')}><option value="week">Build of the Week</option><option value="featured">Featured Build</option></select></label><label>Start date/time<input type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)}/></label><label>End date/time<input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></label><button className="btn btn-primary" type="submit">Save spotlight</button></form><p className="admin-help">Leave the dates blank for an immediate spotlight with no expiry. Build of the Week is limited to one active selection.</p></section><section><h2 className="section-title">Current & scheduled</h2><div className="admin-list">{features.length?features.map(f=><article className="admin-feature" key={f.id}><div><b>{f.kind==='week'?'⭐ BUILD OF THE WEEK':'FEATURED BUILD'}</b><div>{f.build.year} {f.build.make} {f.build.model}{f.build.nickname?' — '+f.build.nickname:''}</div><small>@{f.build.owner.username} · starts {new Date(f.startAt).toLocaleString()}{f.endAt?' · ends '+new Date(f.endAt).toLocaleString():' · no expiry'}</small></div><div className="admin-actions"><Link className="btn btn-ghost" href={'/builds/'+f.build.id}>View</Link><button className="btn btn-ghost" onClick={()=>remove(f.id)}>Unfeature</button></div></article>):<div className="empty"><p className="muted">No manual spotlights configured.</p></div>}</div></section></div>}</section></main>
}
