'use client'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useParams } from 'next/navigation'

type Build={id:string;createdAt:string;ownerId:string;year:number;make:string;model:string;trim?:string|null;nickname?:string|null;description?:string|null;progress:number;budget:number;spent:number;parts:any[];tasks:any[];expenses:any[];journal:any[];owner:{username:string;displayName:string};_count:{comments:number;follows:number;reactions:number}}
type Comment={id:string;content:string;createdAt:string;user:{username:string;displayName:string}}
type Photo={id:string;buildId:string;url:string;caption?:string|null;isCover:boolean;createdAt:string;legacy?:boolean}

export default function BuildPage(){
 const {id}=useParams<{id:string}>(); const [build,setBuild]=useState<Build|null>(null),[comments,setComments]=useState<Comment[]>([]),[photos,setPhotos]=useState<Photo[]>([]),[isOwner,setIsOwner]=useState(false),[following,setFollowing]=useState(false),[liked,setLiked]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false),[comment,setComment]=useState(''),[photoUrl,setPhotoUrl]=useState(''),[photoCaption,setPhotoCaption]=useState('')
 async function load(){const r=await fetch('/api/builds/'+id);const d=await r.json();if(!r.ok)throw Error(d.error);setBuild(d.build);setIsOwner(d.isOwner);setFollowing(d.following);const cr=await fetch('/api/builds/'+id+'/comments');const cd=await cr.json();if(cr.ok)setComments(cd.comments);const pr=await fetch('/api/builds/'+id+'/photos');const pd=await pr.json();if(pr.ok)setPhotos(pd.photos)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[id])
 async function add(path:string,e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget);const r=await fetch('/api/builds/'+id+'/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f.entries()))});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error);return}e.currentTarget.reset();await load()}
 async function addPhoto(e:FormEvent){e.preventDefault();setSaving(true);setError('');try{const r=await fetch('/api/builds/'+id+'/photos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:photoUrl,caption:photoCaption})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error);return}setPhotoUrl('');setPhotoCaption('');await load()}catch{setError('Could not add photo. Please try again.')}finally{setSaving(false)}} 
 async function uploadPhotos(files:FileList|File[]){const list=Array.from(files).filter(f=>f.type.startsWith('image/'));if(!list.length)return;setSaving(true);setError('');try{for(const file of list.slice(0,10)){const dataUrl=await compressImage(file);const r=await fetch('/api/builds/'+id+'/photos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:dataUrl,caption:file.name.replace(/\\.[^/.]+$/,'')})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok)throw Error(d.error||'Upload failed')}await load()}catch(e){setError(e instanceof Error?e.message:'Could not upload photos.')}finally{setSaving(false)}}
 function compressImage(file:File){return new Promise<string>((resolve,reject)=>{const img=new Image();const reader=new FileReader();reader.onload=()=>{img.onload=()=>{const max=2000;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return reject(Error('Image processing failed'));ctx.drawImage(img,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(!blob)return reject(Error('Image compression failed'));if(blob.size>2*1024*1024)return reject(Error('Image is still too large after compression.'));const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=()=>reject(Error('Image read failed'));fr.readAsDataURL(blob)},'image/jpeg',.82)};img.onerror=()=>reject(Error('Invalid image'));img.src=String(reader.result)};reader.onerror=()=>reject(Error('Image read failed'));reader.readAsDataURL(file)})}

 async function setCover(photoId:string){const r=await fetch('/api/builds/'+id+'/photos',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({photoId})});const d=await r.json();if(!r.ok){setError(d.error);return}setPhotos(ps=>ps.map(p=>({...p,isCover:p.id===photoId}))) }
 async function deletePhoto(photoId:string){const r=await fetch('/api/builds/'+id+'/photos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({photoId})});const d=await r.json();if(!r.ok){setError(d.error);return}await load()}
 async function taskStatus(taskId:string,status:string){const r=await fetch('/api/builds/'+id+'/tasks',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId,status})});if(r.ok)await load()}
 async function toggleLike(){const r=await fetch('/api/builds/'+id+'/reaction',{method:'POST'});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error);return}setLiked(d.liked);setBuild(b=>b?{...b,_count:{...b._count,reactions:b._count.reactions+(d.liked?1:-1)}}:b)}
 async function toggleFollow(){const r=await fetch('/api/builds/'+id+'/follow',{method:following?'DELETE':'POST'});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error);return}setFollowing(d.following);await load()}
 async function postComment(e:FormEvent){e.preventDefault();const r=await fetch('/api/builds/'+id+'/comments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:comment})});const d=await r.json();if(r.status===401){location.href='/login';return}if(!r.ok){setError(d.error);return}setComment('');setComments([d.comment,...comments]);setBuild(b=>b?{...b,_count:{...b._count,comments:b._count.comments+1}}:b)}
 if(error&&!build)return <main className="auth-wrap"><div className="auth-card"><p className="error">{error}</p><Link className="small-link" href="/community">Back to community</Link></div></main>
 if(!build)return <main className="auth-wrap"><p className="muted">Loading build…</p></main>
 const cover=photos.find(p=>p.isCover)||photos[0]
 const milestones=[
  {icon:'🏁',title:'Build started',done:true,detail:new Date(build.createdAt).toLocaleDateString()},
  {icon:'📸',title:'First photo',done:photos.length>=1,detail:photos.length+' photo'+(photos.length===1?'':'s')},
  {icon:'🔧',title:'25% complete',done:build.progress>=25,detail:build.progress+'% progress'},
  {icon:'⚙️',title:'50% complete',done:build.progress>=50,detail:build.progress+'% progress'},
  {icon:'🚗',title:'75% complete',done:build.progress>=75,detail:build.progress+'% progress'},
  {icon:'🏆',title:'Build complete',done:build.progress>=100,detail:build.progress+'% progress'},
  {icon:'❤️',title:'10 likes',done:build._count.reactions>=10,detail:build._count.reactions+' likes'},
  {icon:'👥',title:'10 followers',done:build._count.follows>=10,detail:build._count.follows+' followers'}
 ]
 return <main className="dashboard"><header className="topbar"><div className="topbar-inner"><Link className="brand" href="/">BUILD<span>TRACK</span></Link><div className="community-nav"><Link href="/community">Community</Link><Link href="/notifications">🔔 Activity</Link>{isOwner&&<Link href="/dashboard">Garage</Link>}</div></div></header><section className="dash-main">{cover&&<div className="build-cover"><img src={cover.url} alt={cover.caption||build.model}/></div>}<div className="build-public-head"><div><div className="build-meta">{build.year} {build.make}</div><h1>{build.model}</h1><p className="muted">{build.trim||''} {build.nickname?'· '+build.nickname:''}</p><p>Built by <Link className="small-link" href={'/users/'+build.owner.username}>{build.owner.displayName}</Link></p>{build.description&&<p className="public-description">{build.description}</p>}</div><div className="public-actions"><button className="btn btn-primary" onClick={toggleLike}>{liked?'♥ Liked':'♡ Like build'} · {build._count.reactions}</button><button className="btn btn-ghost" onClick={toggleFollow}>{following?'Following':'Follow build'} · {build._count.follows}</button>{isOwner&&<Link className="btn btn-ghost" href="/dashboard">Manage garage</Link>}</div></div>{error&&<div className="error">{error}</div>}
 <div className="feature-grid" style={{padding:0}}><div className="feature"><b>PROGRESS</b><h3>{build.progress}%</h3><div className="progress"><i style={{width:build.progress+'%'}}/></div><p>{build.tasks.filter(t=>t.status==='done').length} of {build.tasks.length} tasks complete</p></div><div className="feature"><b>BUDGET</b><h3>${build.budget.toLocaleString()}</h3><p>${build.spent.toLocaleString()} spent</p></div><div className="feature"><b>PARTS</b><h3>{build.parts.length}</h3><p>{build._count.reactions} likes · {build._count.comments} comments · {build._count.follows} followers</p></div></div>
 <div className="panel milestone-panel"><div className="panel-head"><div><h2>Build milestones</h2><p className="muted">Track the moments that mark this project's progress.</p></div></div><div className="milestone-list">{milestones.map(m=><div className={'milestone'+(m.done?' complete':'')} key={m.title}><span className="milestone-icon">{m.icon}</span><div><b>{m.title}</b><small>{m.detail}</small></div><strong>{m.done?'✓':'—'}</strong></div>)}</div></div><div className="panel photo-panel"><div className="panel-head"><div><h2>Build gallery</h2><p className="muted">Show the community what you're building.</p></div></div>{isOwner&&<><div className="photo-upload"><label className="drop-zone"><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" multiple onChange={e=>e.target.files&&uploadPhotos(e.target.files)} disabled={saving}/><strong>{saving?'Uploading…':'Drop photos here or click to browse'}</strong><span>JPG, PNG, WEBP or GIF · up to 10 photos at a time</span></label></div><form className="inline-form" onSubmit={addPhoto}><input value={photoUrl} onChange={e=>setPhotoUrl(e.target.value)} placeholder="Paste image URL…"/><input value={photoCaption} onChange={e=>setPhotoCaption(e.target.value)} placeholder="Caption (optional)"/><button className="btn btn-primary" disabled={saving||!photoUrl}>Add photo</button></form></>}<div className="photo-grid">{photos.map(p=><figure className={'photo-card'+(p.isCover?' is-cover':'')} key={p.id}><img src={p.url} alt={p.caption||'Build photo'} loading="lazy"/><figcaption><span>{p.caption||'Build photo'}{p.isCover&&<b> COVER</b>}</span>{isOwner&&!p.legacy&&<span className="photo-actions"><button type="button" className="small-link" onClick={()=>setCover(p.id)} disabled={p.isCover}>Set cover</button><button type="button" className="danger-link" onClick={()=>deletePhoto(p.id)}>Delete</button></span>}</figcaption></figure>)}{!photos.length&&<div className="empty"><p className="muted">No photos yet. Add the first look at this build.</p></div>}</div></div>
 <div className="public-grid"><div><div className="panel"><h2>Build journal</h2><div className="list">{build.journal.map(j=><article className="journal" key={j.id}><small>{new Date(j.createdAt).toLocaleDateString()}</small><h3>{j.title}</h3><p>{j.content}</p></article>)}{!build.journal.length&&<p className="muted">No journal entries yet.</p>}</div></div><div className="panel comments-panel"><h2>Comments</h2><form className="inline-form" onSubmit={postComment}><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Leave a comment…" required/><button className="btn btn-primary">Post</button></form><div className="list">{comments.map(c=><div className="comment" key={c.id}><b><Link className="small-link" href={'/users/'+c.user.username}>{c.user.displayName}</Link></b><small>{new Date(c.createdAt).toLocaleDateString()}</small><p>{c.content}</p></div>)}{!comments.length&&<p className="muted">Be the first to comment.</p>}</div></div></div>{isOwner?<div className="panel"><h2>Manage build</h2><p className="muted">Only you can change your parts, tasks, expenses and journal.</p><div className="list">{build.parts.slice(0,8).map(p=><div className="list-row" key={p.id}><div><b>{p.name}</b><small>{p.manufacturer||'No manufacturer'} · {p.status}</small></div><strong>${Number(p.price).toLocaleString()}</strong></div>)}{!build.parts.length&&<p className="muted">No parts tracked yet.</p>}</div><div className="manage-grid" style={{marginTop:16}}><div className="panel"><h3>Add part</h3><form className="form" onSubmit={e=>add('parts',e)}><input name="name" placeholder="Part name" required/><input name="manufacturer" placeholder="Manufacturer"/><input name="price" type="number" step=".01" placeholder="Price"/><button className="btn btn-primary" disabled={saving}>Add part</button></form></div><div className="panel"><h3>Add task</h3><form className="form" onSubmit={e=>add('tasks',e)}><input name="name" placeholder="Task" required/><button className="btn btn-primary" disabled={saving}>Add task</button></form></div></div><div className="list" style={{marginTop:16}}>{build.tasks.map(t=><div className="list-row" key={t.id}><button className="check" onClick={()=>taskStatus(t.id,t.status==='done'?'todo':'done')}>{t.status==='done'?'✓':'○'}</button><b className={t.status==='done'?'done':''}>{t.name}</b></div>)}</div></div>:<div className="panel"><h2>About this build</h2><p className="muted">Follow this project to keep up with updates, then join the conversation in the comments.</p><Link className="btn btn-primary" href={'/users/'+build.owner.username}>View builder profile</Link></div>}</div></section></main>
}